/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LeaderRouteImport } from './routes/leader'
import { Route as MemberRouteImport } from './routes/member'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as HomeDepartmentRouteImport } from './routes/home.department'
import { Route as HomeMeetingsRouteImport } from './routes/home.meetings'
import { Route as HomeMembersRouteImport } from './routes/home.members'
import { Route as HomeNotificationsRouteImport } from './routes/home.notifications'
import { Route as HomeReportsRouteImport } from './routes/home.reports'
import { Route as HomeRequestsRouteImport } from './routes/home.requests'
import { Route as HomeRiskAlertsRouteImport } from './routes/home.risk-alerts'
import { Route as HomeSettingsRouteImport } from './routes/home.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderRoute = LeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeDepartmentRoute = HomeDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMeetingsRoute = HomeMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMembersRoute = HomeMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => HomeRoute,
} as any)
const HomeNotificationsRoute = HomeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HomeRoute,
} as any)
const HomeReportsRoute = HomeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HomeRoute,
} as any)
const HomeRequestsRoute = HomeRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => HomeRoute,
} as any)
const HomeRiskAlertsRoute = HomeRiskAlertsRouteImport.update({
  id: '/risk-alerts',
  path: '/risk-alerts',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/leader': typeof LeaderRoute
  '/member': typeof MemberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home/department': typeof HomeDepartmentRoute
  '/home/meetings': typeof HomeMeetingsRoute
  '/home/members': typeof HomeMembersRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/requests': typeof HomeRequestsRoute
  '/home/risk-alerts': typeof HomeRiskAlertsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leader': typeof LeaderRoute
  '/member': typeof MemberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home/department': typeof HomeDepartmentRoute
  '/home/meetings': typeof HomeMeetingsRoute
  '/home/members': typeof HomeMembersRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/requests': typeof HomeRequestsRoute
  '/home/risk-alerts': typeof HomeRiskAlertsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/leader': typeof LeaderRoute
  '/member': typeof MemberRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home/department': typeof HomeDepartmentRoute
  '/home/meetings': typeof HomeMeetingsRoute
  '/home/members': typeof HomeMembersRoute
  '/home/notifications': typeof HomeNotificationsRoute
  '/home/reports': typeof HomeReportsRoute
  '/home/requests': typeof HomeRequestsRoute
  '/home/risk-alerts': typeof HomeRiskAlertsRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/home'
    | '/leader'
    | '/member'
    | '/reset-password'
    | '/signup'
    | '/home/department'
    | '/home/meetings'
    | '/home/members'
    | '/home/notifications'
    | '/home/reports'
    | '/home/requests'
    | '/home/risk-alerts'
    | '/home/settings'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/leader'
    | '/member'
    | '/reset-password'
    | '/signup'
    | '/home/department'
    | '/home/meetings'
    | '/home/members'
    | '/home/notifications'
    | '/home/reports'
    | '/home/requests'
    | '/home/risk-alerts'
    | '/home/settings'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/home'
    | '/leader'
    | '/member'
    | '/reset-password'
    | '/signup'
    | '/home/department'
    | '/home/meetings'
    | '/home/members'
    | '/home/notifications'
    | '/home/reports'
    | '/home/requests'
    | '/home/risk-alerts'
    | '/home/settings'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRouteWithChildren
  LeaderRoute: typeof LeaderRoute
  MemberRoute: typeof MemberRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader': {
      id: '/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof LeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/department': {
      id: '/home/department'
      path: '/department'
      fullPath: '/home/department'
      preLoaderRoute: typeof HomeDepartmentRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/meetings': {
      id: '/home/meetings'
      path: '/meetings'
      fullPath: '/home/meetings'
      preLoaderRoute: typeof HomeMeetingsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/members': {
      id: '/home/members'
      path: '/members'
      fullPath: '/home/members'
      preLoaderRoute: typeof HomeMembersRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/notifications': {
      id: '/home/notifications'
      path: '/notifications'
      fullPath: '/home/notifications'
      preLoaderRoute: typeof HomeNotificationsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/reports': {
      id: '/home/reports'
      path: '/reports'
      fullPath: '/home/reports'
      preLoaderRoute: typeof HomeReportsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/requests': {
      id: '/home/requests'
      path: '/requests'
      fullPath: '/home/requests'
      preLoaderRoute: typeof HomeRequestsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/risk-alerts': {
      id: '/home/risk-alerts'
      path: '/risk-alerts'
      fullPath: '/home/risk-alerts'
      preLoaderRoute: typeof HomeRiskAlertsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeDepartmentRoute: typeof HomeDepartmentRoute
  HomeMeetingsRoute: typeof HomeMeetingsRoute
  HomeMembersRoute: typeof HomeMembersRoute
  HomeNotificationsRoute: typeof HomeNotificationsRoute
  HomeReportsRoute: typeof HomeReportsRoute
  HomeRequestsRoute: typeof HomeRequestsRoute
  HomeRiskAlertsRoute: typeof HomeRiskAlertsRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeDepartmentRoute: HomeDepartmentRoute,
  HomeMeetingsRoute: HomeMeetingsRoute,
  HomeMembersRoute: HomeMembersRoute,
  HomeNotificationsRoute: HomeNotificationsRoute,
  HomeReportsRoute: HomeReportsRoute,
  HomeRequestsRoute: HomeRequestsRoute,
  HomeRiskAlertsRoute: HomeRiskAlertsRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRouteWithChildren,
  LeaderRoute: LeaderRoute,
  MemberRoute: MemberRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
